### ISSUE TITLE
Error when trying to set alpha value

### ISSUE THREAD

**Issue by codingfar** [steveberardi/starplot#43]
Using the code `style.constellation_borders.alpha = 0` or, for example, `style.bayer_labels.font_size = 15` works just fine, but inserting the code `style.gridlines.alpha = 0 ` returns: ValueError: "PathStyle" object has no field "alpha".
The same occurs if one tries, say, `style.celestial_equator.alpha = 0`. The code I was trying to use is copied below.

------------------------------------------------------

```
from starplot import PlotStyle, MapPlot, Projection

style = PlotStyle()
style.bayer_labels.font_name = "Times New Roman"
style.bayer_labels.font_size = 15
style.constellation_borders.alpha = 0
style.milky_way.alpha = 0
style.gridlines.alpha = 0


p = MapPlot(
    projection=Projection.MERCATOR,
    ra_min=4.6,
    ra_max=6.4,
    dec_min=-16,
    dec_max=23.6,
    limiting_magnitude=6.0,
    style=style,
    resolution=3600,
)

p.export("test.png", padding=0.5)

```

Alternatively, trying to create a style using a YAML file did not work. I tried the following code (adapted from the "More Complex Example" on the website):

```
from starplot import PlotStyle, MapPlot, Projection
from starplot.styles import LineStyle, ObjectStyle, PathStyle

style = PlotStyle.load_from_file("/Users/josephcaruana/Downloads/check/style.yml")

p = MapPlot(
    projection=Projection.MERCATOR,
    ra_min=4.6,
    ra_max=6.5,
    dec_min=-16,
    dec_max=23.6,
    style=style,
)

p.export("figure.png", padding=0.5)
```

I used the following YAML file:

```
# style.yml

# hide the constellation labels/lines:
constellation:
  label:
    visible: false
  line:
    visible: false

# make the Milky Way gray
milky_way:
  visible: false

# change the color of star labels to blue and
# and change their symbol from dots to stars
star:
  label:
    font_color: '#0e69b8'
  marker:
    symbol: '*'

# make nebulas green and their markers diamonds
dso_nebula:
  marker:
    color: green
    symbol: D
```

However, although this did not return any errors, none of the chosen style options were implemented in the chart that was produced.
